import type { Metadata } from 'next'
import { createClient } from '@supabase/supabase-js'
import { Providers } from './providers'
import { Toaster } from '@/components/ui/sonner'
import { satoshi } from './fonts/fonts'

import './globals.css'

// Added the parameters below to use Supabase client libraries. (possibly abstract this)
const supabaseUrl = 'https://ypnkyijseyxxsorzkphd.supabase.co'
const supabaseKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwbmt5aWpzZXl4eHNvcnprcGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjcwMjYyNzYsImV4cCI6MjA0MjYwMjI3Nn0.rnJyEEsi2qbgNzzgBKI9NpsIrh_DZsHBj6MFJ5uoIvk'
const supabase = createClient(supabaseUrl, supabaseKey)

export const metadata: Metadata = {
  title: 'expense tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${satoshi.variable} font-sans`}>
        <Providers>
          {children}
          <Toaster position='bottom-left' richColors closeButton />
        </Providers>
      </body>
    </html>
  )
}
